site_name: Документация LWC
site_url: https://daniel-robotic.github.io/lightweight-cobot/
site_description: Документация по использованию коллаборативного робота KUKA LBR iiwa 7 и его программированию в среде ROS 2.
site_author: Даниил Грабарь

theme:
  name: material
  custom_dir: overrides
  language: ru
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight

plugins:
  - search
  - to-pdf:
      author: Даниил Грабарь
      cover_title: Документация LWC
      cover_subtitle: Lightweight Cobot
      output_path: pdf/documentation.pdf

extra_css:
  - assets/extra.css

extra_javascript:
  - assets/pdf_button.js

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - Главная: index.md

  - Быстрый старт:
    - Обзор: getting-started/overview.md
    - Быстрый старт: getting-started/quick-start.md
    - Ручная установка: getting-started/manual-sun_install.md
    - Настройка: getting-started/configuration.md

  - Sunrise Workbench:
    - Обзор: sunrise/overview.md
    - Установка:
      - Windows: sunrise/sun_install/windows.md
      - Linux:
        - Обзор: sunrise/sun_install/linux/linux.md
        - Установка эмулятора Windows: sunrise/sun_install/linux/emulator.md
        - Установка SunriseWorkbench: sunrise/sun_install/linux/workbench.md
    - Конфигурация проекта:
      - Создание нового проекта: sunrise/config/new-project.md
      - Загрузка готового проекта: sunrise/config/load-project.md
      - Установка библиотек: sunrise/config/libraries.md
    - KUKA LBR IIWA 7:
      - Описание программ:
        - TeachKuka: sunrise/kuka/programs/teach-kuka.md
        - LBRserver: sunrise/kuka/programs/lbr-server.md
        - RobotPowerControl: sunrise/kuka/programs/robot-power-control.md
      - Функциональные возможности:
        - Станция: sunrise/kuka/features/station.md
        - Дополнительное меню: sunrise/kuka/features/extra-menu.md
        - Приложения: sunrise/kuka/features/applications.md
        - Меню робота: sunrise/kuka/features/robot-menu.md
        - Меню IO Group: sunrise/kuka/features/io-group.md
    - Решение проблем:
      - Ошибка конфигурации: sunrise/troubleshooting/config-error.md


